#some of these imports are extraneous and left over from the flask megatutorial 
from flask import render_template, flash, redirect, url_for, request, Flask, jsonify, send_from_directory
from app import app, db, DataWizardTools
from app.models import User, Post
from app.forms import PostForm
from werkzeug.urls import url_parse
from datetime import datetime
import pandas as pd
import os

@app.route("/RadSearcher", methods=['GET', 'POST'])
def RadSearcher():
    #upload file from computer
    if request.method == 'POST':
        print(request.files['file'])
        f = request.files['file']
        
        #turn the excel file into a dataframe, but skip the top 2 rows if they are blank
        test = pd.read_excel(f)
        test.fillna('',inplace=True)
        if test.iloc[0][0] == '':
            df = pd.read_excel(f,skiprows=2)
        else:
            df = pd.read_excel(f)

        
        #Remove Rows without Case ID values
        df.fillna('',inplace = True)
        df['Matter/Case ID#'] = df.apply(lambda x : DataWizardTools.RemoveNoCaseID(x['Matter/Case ID#']),axis=1)        
        df = df[df['Matter/Case ID#'] != 'No Case ID']
        

        #Create Hyperlinks
        df['Hyperlinked CaseID#'] = df.apply(lambda x : DataWizardTools.Hyperlinker(x['Matter/Case ID#']),axis=1)     
        
        #List of abbreviated RAD addresses
        RADBuildings = ["54-81 ALMEDA",
                        "54-75 ALMEDA",
                        "54-49 ALMEDA",
                        "54-41 ALMEDA",
                        "54-15 ALMEDA",
                        "54-09 ALMEDA",
                        "51-49 ALMEDA",
                        "51-45 ALMEDA",
                        "51-15 ALMEDA",
                        "51-11 ALMEDA",
                        "409 BEACH 51ST",
                        "51-24 BEACH CHANNEL",
                        "51-32 BEACH CHANNEL",
                        "410 BEACH 54TH",
                        "411 BEACH 54TH",
                        "54-22 BEACH CHANNEL",
                        "54-30 BEACH CHANNEL",
                        "56-10 BEACH CHANNEL",
                        "56-16 BEACH CHANNEL",
                        "414 BEACH 58TH",
                        "57-10 BEACH CHANNEL",
                        "441 BEACH 51ST",
                        "445 BEACH 51ST",
                        "430 BEACH 54TH",
                        "434 BEACH 54TH",
                        "440 BEACH 54TH",
                        "444 BEACH 54TH",
                        "439 BEACH 54TH",
                        "443 BEACH 54TH",
                        "447 BEACH 54TH",
                        "434 BEACH 58TH",
                        "440 BEACH 58TH",
                        "371 EAST 183RD",
                        "380 EAST 183RD",
                        "390 EAST 184TH",
                        "394 EAST 184TH",
                        "386 FORD",
                        "2251 WEBSTER",
                        "2273 WEBSTER",
                        "2291 WEBSTER",
                        "2303 WEBSTER",
                        "365 FORD",
                        "360 FORD",
                        "365 FORD",
                        "365 FORD",
                        "353 FORD",
                        "355 FORD",
                        "365 FORD",
                        "365 EAST 183RD",
                        "365 FORD",
                        "365 EAST 183RD",
                        "355 EAST 183RD",
                        "365 EAST 183RD",
                        "400 BROOK",
                        "404 BROOK",
                        "510 EAST 144TH",
                        "511 EAST 143RD",
                        "515 EAST 143RD",
                        "525 EAST 143RD",
                        "531 EAST 143RD",
                        "535 EAST 143RD",
                        "545 EAST 143RD",
                        "551 EAST 143RD",
                        "555 EAST 143RD",
                        "401 SAINT ANNS",
                        "560 EAST 144TH",
                        "550 EAST 144TH",
                        "540 EAST 144TH",
                        "530 EAST 144TH",
                        "520 EAST 144TH",
                        "690 EAST 140TH",
                        "700 EAST 140TH",
                        "443 EAST 137TH",
                        "453 EAST 137TH",
                        "455 EAST 137TH",
                        "463 EAST 137TH",
                        "408 EAST 137TH",
                        "416 EAST 137TH",
                        "505 EAST 144TH",
                        "509 EAST 144TH",
                        "511 EAST 144TH",
                        "517 EAST 144TH",
                        "695 EAST 139TH",
                        "699 EAST 139TH",
                        "451 EAST 136TH",
                        "411 EAST 136TH",
                        "427 SAINT ANNS",
                        "423 SAINT ANNS",
                        "480 EAST 143RD",
                        "490 EAST 143RD",
                        "433 EAST 146TH",
                        "435 EAST 146TH",
                        "437 EAST 146TH",
                        "439 EAST 146TH",
                        "441 EAST 146TH",
                        "511 EAST 146TH",
                        "513 EAST 146TH",
                        "417 EAST 146TH",
                        "419 EAST 146TH",
                        "421 EAST 146TH",
                        "423 EAST 146TH",
                        "425 EAST 146TH",
                        "427 EAST 146TH",
                        "429 EAST 146TH",
                        "431 EAST 146TH",
                        "527 EAST 146TH",
                        "537 EAST 146TH",
                        "545 EAST 146TH",
                        "510 EAST 146TH",
                        "512 EAST 146TH",
                        "528 EAST 146TH",
                        "530 EAST 146TH",
                        "455 EAST 146TH",
                        "547 EAST 146TH",
                        "450 EAST 143RD",
                        "521 EAST 146TH",
                        "525 EAST 146TH",
                        "521 EAST 145TH",
                        "525 EAST 145TH",
                        "409 EAST 146TH",
                        "411 EAST 146TH",
                        "413 EAST 146TH",
                        "415 EAST 146TH",
                        "445 EAST 146TH",
                        "400 EAST 147TH",
                        "460 EAST 147TH",
                        "550 EAST 147TH",
                        "474 WILLIS",
                        "465 SAINT ANNS",
                        "1381 FRANKLIN",
                        "1383 FRANKLIN",
                        "1377 FRANKLIN",
                        "1379 FRANKLIN",
                        "1373 FRANKLIN",
                        "1385 FRANKLIN",
                        "1394 FRANKLIN",
                        "1392 FRANKLIN",
                        "1390 FRANKLIN",
                        "631 JEFFERSON",
                        "1085 ANDERSON",
                        "130 WEST 166TH",
                        "134 WEST 166TH",
                        "125 WEST 166TH",
                        "1125 NELSON",
                        "1127 NELSON",
                        "1135 NELSON",
                        "1182 NELSON",
                        "1184 NELSON",
                        "1144 NELSON",
                        "1139 NELSON",
                        "1225 EAST 225TH",
                        "1860 SCHIEFFELIN",
                        "1870 SCHIEFFELIN",
                        "1880 SCHIEFFELIN",
                        "1890 SCHIEFFELIN",
                        "1920 SCHIEFFELIN",
                        "1930 SCHIEFFELIN",
                        "1900 SCHIEFFELIN",
                        "1910 SCHIEFFELIN",
                        "1861 SCHIEFFELIN",
                        "1881 SCHIEFFELIN",
                        "1851 SCHIEFFELIN",
                        "1871 SCHIEFFELIN",
                        "1891 SCHIEFFELIN",
                        "1220 EAST 229TH",
                        "1805 CROTONA",
                        "1807 CROTONA",
                        "1811 CROTONA",
                        "601 CROTONA PARK",
                        "611 CROTONA PARK",
                        "615 CROTONA PARK",
                        "580 CENTRAL",
                        "155 ELDERT",
                        "595 EVERGREEN",
                        "615 EVERGREEN",
                        "690 EVERGREEN",
                        "670 EVERGREEN",
                        "85 COVERT",
                        "75 COVERT",
                        "160 HIMROD",
                        "140 HIMROD",
                        "139 HARMAN",
                        "251 CENTRAL",
                        "270 CENTRAL",
                        "290 CENTRAL",
                        "310 CENTRAL",
                        "250 WILSON",
                        "190 HARMAN",
                        "1259 GREENE",
                        "140 HARMAN",
                        "1229 GREENE",
                        "269 CENTRAL",
                        "270 WILSON",
                        "1280 GREENE",
                        "1240 GREENE",
                        "289 CENTRAL",
                        "1201 GATES",
                        "415 EVERGREEN",
                        "431 EVERGREEN",
                        "1210 GATES",
                        "1230 GATES",
                        "1240 GATES",
                        "1260 GATES",
                        "400 CENTRAL",
                        "143 PALMETTO",
                        "125 PALMETTO",
                        "105 PALMETTO",
                        "95 PALMETTO",
                        "440 CENTRAL",
                        "1320 GATES",
                        "1300 GATES",
                        "375 CENTRAL",
                        "161 PALMETTO",
                        "390 WILSON",
                        "210 PALMETTO",
                        "200 PALMETTO",
                        "190 PALMETTO",
                        "191 WOODBINE",
                        "180 PALMETTO",
                        "170 PALMETTO",
                        "399 CENTRAL",
                        "420 CENTRAL",
                        "422 CENTRAL",
                        "1387 GATES",
                        "230 LINDEN",
                        "176 MENAHAN",
                        "172 MENAHAN",
                        "319 WILSON",
                        "323 WILSON",
                        "327 WILSON",
                        "242 GROVE",
                        "238 GROVE",
                        "234 GROVE",
                        "230 GROVE",
                        "226 GROVE",
                        "339 WILSON",
                        "343 WILSON",
                        "347 WILSON",
                        "235 LINDEN",
                        "239 LINDEN",
                        "243 LINDEN",
                        "247 LINDEN",
                        "251 LINDEN",
                        "532 KNICKERBOCKER",
                        "528 KNICKERBOCKER",
                        "524 KNICKERBOCKER",
                        "236 LINDEN",
                        "232 LINDEN",
                        "228 LINDEN",
                        "224 LINDEN",
                        "220 LINDEN",
                        "357 WILSON",
                        "361 WILSON",
                        "365 WILSON",
                        "1389 GATES",
                        "1393 GATES",
                        "1397 GATES",
                        "1411 GATES",
                        "1415 GATES",
                        "558 KNICKERBOCKER",
                        "554 KNICKERBOCKER",
                        "550 KNICKERBOCKER",
                        "331 CENTRAL",
                        "120 MENAHAN",
                        "140 MENAHAN",
                        "160 MENAHAN",
                        "314 WILSON",
                        "195 LINDEN",
                        "330 WILSON",
                        "85 PALMETTO",
                        "590 WARREN",
                        "568 WARREN",
                        "572 WARREN",
                        "565 BALTIC",
                        "574 WARREN",
                        "513 GREENE",
                        "362 CLIFTON",
                        "360 CLIFTON",
                        "358 CLIFTON",
                        "356 CLIFTON",
                        "354 CLIFTON",
                        "352 CLIFTON",
                        "350 CLIFTON",
                        "348 CLIFTON",
                        "346 CLIFTON",
                        "344 CLIFTON",
                        "366 CLIFTON",
                        "380 CLIFTON",
                        "388 CLIFTON",
                        "396 CLIFTON",
                        "545 GREENE",
                        "555 GREENE",
                        "304 LEXINGTON",
                        "302 LEXINGTON",
                        "300 LEXINGTON",
                        "298 LEXINGTON",
                        "296 LEXINGTON",
                        "294 LEXINGTON",
                        "292 LEXINGTON",
                        "290 LEXINGTON",
                        "288 LEXINGTON",
                        "286 LEXINGTON",
                        "284 LEXINGTON",
                        "282 LEXINGTON",
                        "280 LEXINGTON",
                        "278 LEXINGTON",
                        "310 LEXINGTON",
                        "320 LEXINGTON",
                        "330 LEXINGTON",
                        "336 LEXINGTON",
                        "435 GATES",
                        "441 GATES",
                        "447 GATES",
                        "449 GATES",
                        "451 GATES",
                        "453 GATES",
                        "455 GATES",
                        "457 GATES",
                        "459 GATES",
                        "461 GATES",
                        "463 GATES",
                        "465 GATES",
                        "467 GATES",
                        "469 GATES",
                        "471 GATES",
                        "473 GATES",
                        "475 GATES",
                        "360 NOSTRAND",
                        "260 LEXINGTON",
                        "262 LEXINGTON",
                        "264 LEXINGTON",
                        "254 LEXINGTON",
                        "252 LEXINGTON",
                        "252A LEXINGTON",
                        "250 LEXINGTON",
                        "375 LEXINGTON",
                        "385 LEXINGTON",
                        "395 LEXINGTON",
                        "405 LEXINGTON",
                        "415 LEXINGTON",
                        "280 TOMPKINS",
                        "360 LEXINGTON",
                        "370 LEXINGTON",
                        "380 LEXINGTON",
                        "390 LEXINGTON",
                        "775 MARCY",
                        "785 MARCY",
                        "791 MARCY",
                        "499 GATES",
                        "505 GATES",
                        "515 GATES",
                        "495 GATES",
                        "462 BEDFORD",
                        "464 BEDFORD",
                        "466 BEDFORD",
                        "447 BERRY",
                        "448 BERRY",
                        "449 BERRY",
                        "450 BERRY",
                        "451 BERRY",
                        "453 BERRY",
                        "455 BERRY",
                        "100 SOUTH 10TH",
                        "45 SOUTH 10TH",
                        "49 SOUTH 10TH",
                        "51 SOUTH 10TH",
                        "53 SOUTH 10TH",
                        "55 SOUTH 10TH",
                        "57 SOUTH 10TH",
                        "59 SOUTH 10TH",
                        "61 SOUTH 10TH",
                        "63 SOUTH 10TH",
                        "65 SOUTH 10TH",
                        "65A SOUTH 10TH",
                        "67 SOUTH 10TH",
                        "74 SOUTH 9TH",
                        "440 BERRY",
                        "71 SOUTH 10TH",
                        "46 SOUTH 9TH",
                        "50 SOUTH 9TH",
                        "54 SOUTH 9TH",
                        "58 SOUTH 9TH",
                        "46 SOUTH 10TH",
                        "48 SOUTH 10TH",
                        "52 SOUTH 10TH",
                        "56 SOUTH 10TH",
                        "60 SOUTH 10TH",
                        "64 SOUTH 10TH",
                        "84 SOUTH 10TH",
                        "88 SOUTH 10TH",
                        "92 SOUTH 10TH",
                        "96 SOUTH 10TH",
                        "83 TAYLOR",
                        "85 TAYLOR",
                        "128 CLYMER",
                        "130 CLYMER",
                        "140 CLYMER",
                        "119 TAYLOR",
                        "123 TAYLOR",
                        "125 TAYLOR",
                        "114 TAYLOR",
                        "119 WILSON",
                        "121 WILSON",
                        "110 TAYLOR",
                        "95 WILSON",
                        "97 WILSON",
                        "99 WILSON",
                        "73 WILSON",
                        "75 WILSON",
                        "534 GREENE",
                        "528 GREENE",
                        "524 GREENE",
                        "518 GREENE",
                        "323 LEXINGTON",
                        "325 LEXINGTON",
                        "327 LEXINGTON",
                        "329 LEXINGTON",
                        "331 LEXINGTON",
                        "492 GREENE",
                        "494 GREENE",
                        "496 GREENE",
                        "305 LEXINGTON",
                        "303 NOSTRAND",
                        "305 NOSTRAND",
                        "307 NOSTRAND",
                        "309 NOSTRAND",
                        "311 LEXINGTON",
                        "313 LEXINGTON",
                        "315 LEXINGTON",
                        "317 LEXINGTON",
                        "319 LEXINGTON",
                        "1625 DEAN",
                        "1615 DEAN",
                        "1605 DEAN",
                        "1595 DEAN",
                        "1585 DEAN",
                        "1575 DEAN",
                        "87 TROY",
                        "1620 PACIFIC",
                        "1630 PACIFIC",
                        "1640 PACIFIC",
                        "1642 PACIFIC",
                        "1650 PACIFIC",
                        "1660 PACIFIC",
                        "1670 PACIFIC",
                        "1672 PACIFIC",
                        "80 SCHENECTADY",
                        "321 ROEBLING",
                        "323 ROEBLING",
                        "325 ROEBLING",
                        "327 ROEBLING",
                        "333 ROEBLING",
                        "195 DIVISION",
                        "253 HAVEMEYER",
                        "255 HAVEMEYER",
                        "188 MARCY",
                        "190 MARCY",
                        "221 DIVISION",
                        "223 DIVISION",
                        "225 DIVISION",
                        "227 DIVISION",
                        "335 EAST 111TH",
                        "340 EAST 28TH",
                        "342 EAST 28TH",
                        "344 EAST 28TH",
                        "346 EAST 28TH",
                        "99 FORT WASHINGTON",
                        "2340 AMSTERDAM",
                        "501 WEST 176TH",
                        "2346 AMSTERDAM",
                        "500 WEST 177TH",
                        "503 WEST 177TH",
                        "511 WEST 177TH",
                        "506 WEST 177TH",
                        "514 WEST 177TH",
                        "509 WEST 176TH",
                        "545 WEST 156TH",
                        "450 WEST 164TH",
                        "457 WEST 164TH",
                        "461 WEST 164TH",
                        "463 WEST 164TH",
                        "465 WEST 164TH",
                        "500 WEST 164TH",
                        "2109 AMSTERDAM",
                        "2111 AMSTERDAM",
                        "502 WEST 177TH",
                        "506 WEST 176TH",
                        "510 WEST 176TH",
                        "514 WEST 176TH",
                        "182 SAINT NICHOLAS",
                        "515 WEST 134TH",
                        "511 WEST 134TH",
                        "1504 AMSTERDAM",
                        "529 WEST 133RD",
                        "514 WEST 134TH",
                        "120 EAST 123RD",
                        "115 EAST 122ND",
                        "114 EAST 123RD",
                        "116 EAST 123RD",
                        "120 WEST 140TH",
                        "2405 A C POWELL",
                        "2403 A C POWELL",
                        "2401 A C POWELL",
                        "173 WEST 140TH",
                        "138 WEST 139TH",
                        "136 WEST 139TH",
                        "110 WEST 139TH",
                        "151 WEST 142ND",
                        "153 WEST 142ND",
                        "111 WEST 90TH",
                        "117 WEST 90TH",
                        "114 WEST 91ST",
                        "124 WEST 91ST",
                        "120 WEST 91ST",
                        "133 WEST 90TH",
                        "136 WEST 91ST",
                        "141 WEST 90TH",
                        "1909 AMSTERDAM",
                        "1943 AMSTERDAM",
                        "1945 AMSTERDAM",
                        "1947 AMSTERDAM",
                        "1949 AMSTERDAM",
                        "1968 AMSTERDAM",
                        "1970 AMSTERDAM",
                        "455 BARBEY",
                        "459 BARBEY",
                        "463 BARBEY",
                        "418 JEROME",
                        "422 JEROME",
                        "426 JEROME",
                        "610 BELMONT",
                        "616 BELMONT",
                        "2150 LINDEN",
                        "785 SCHENCK",
                        "797 SCHENCK",
                        "817 SCHENCK",
                        "829 SCHENCK",
                        "2156 LINDEN",
                        "807 SCHENCK",
                        "725 STANLEY",
                        "2202 LINDEN",
                        "830 ASHFORD",
                        "765 STANLEY",
                        "804 ASHFORD",
                        "812 ASHFORD",
                        "828 ASHFORD",
                        "816 ASHFORD",
                        "842 ASHFORD",
                        "854 ASHFORD",
                        "773 STANLEY",
                        "845 SCHENCK",
                        "857 SCHENCK",
                        "881 SCHENCK",
                        "893 SCHENCK",
                        "260 BRADFORD",
                        "2155 PITKIN",
                        "2165 PITKIN",
                        "2185 PITKIN",
                        "2189 PITKIN",
                        "2181 PITKIN",
                        "330 MILLER",
                        "340 MILLER",
                        "320 MILLER",
                        "2211 PITKIN",
                        "2215 PITKIN",
                        "2221 PITKIN",
                        "2219 PITKIN",
                        "229 WEST 152ND",
                        "225 WEST 152ND",
                        "221 WEST 152ND",
                        "210T WEST 153RD",
                        "210S WEST 153RD",
                        "210R WEST 153RD",
                        "210Q WEST 153RD",
                        "70 MACOMBS",
                        "210P WEST 153RD",
                        "210N WEST 153RD",
                        "210M WEST 153RD",
                        "210L WEST 153RD",
                        "2650 A C POWELL",
                        "210K WEST 153RD",
                        "211J WEST 151ST",
                        "211H WEST 151 ST",
                        "2628 A C POWELL",
                        "2630 A C POWELL",
                        "2632 A C POWELL",
                        "211G WEST 151ST",
                        "2620 A C POWELL",
                        "2622 A C POWELL",
                        "2624 A C POWELL",
                        "2626 A C POWELL",
                        "211F WEST 151 ST",
                        "207 WEST 151ST",
                        "211E WEST 151ST",
                        "211D WEST 151 ST",
                        "211C WEST 151 ST",
                        "211B WEST 151ST",
                        "211A WEST 151ST",
                        "220 WEST 152ND",
                        "224 WEST 152ND",
                        "226 WEST 152ND",
                        "231 WEST 151ST",
                        "234 WEST 152ND",
                        "52 MACOMBS",
                        "54 MACOMBS",
                        "54 1/2 MACOMBS",
                        "56 MACOMBS",
                        "56 1/2 MACOMBS",
                        "58 MACOMBS",
                        "58 1/2 MACOMBS",
                        "50 MACOMBS",
                        "48 MACOMBS",
                        "46 MACOMBS",
                        "40 1/2 MACOMBS",
                        "42 MACOMBS",
                        "42 1/2 MACOMBS",
                        "44 MACOMBS",
                        "2653 A C POWELL",
                        "2651 A C POWELL",
                        "2645 A C POWELL",
                        "2641 A C POWELL",
                        "187 WEST 152ND",
                        "183 WEST 152ND",
                        "180 WEST 152ND",
                        "182 WEST 152ND",
                        "186 WEST 152ND",
                        "2637 A C POWELL",
                        "190 WEST 152ND",
                        "2627 A C POWELL",
                        "2633 A C POWELL",
                        "191W WEST 151ST",
                        "2621 A C POWELL",
                        "191V WEST 151ST",
                        "191U WEST 151 ST",
                        "181 WEST 151ST",
                        "177 WEST 151ST",
                        "173 WEST 151 ST",
                        "2850 FREDERICK DOUGLASS",
                        "291 WEST 151ST",
                        "293 WEST 151ST",
                        "295 WEST 151ST",
                        "570 STANLEY",
                        "580 STANLEY",
                        "630 STANLEY",
                        "640 STANLEY",
                        "912 VAN SICLEN",
                        "914 VAN SICLEN",
                        "243 WORTMAN",
                        "245 WORTMAN",
                        "247 WORTMAN",
                        "225 WORTMAN",
                        "215 WORTMAN",
                        "183 WORTMAN",
                        "185 WORTMAN",
                        "187 WORTMAN",
                        "180 WORTMAN",
                        "190 WORTMAN",
                        "240 WORTMAN",
                        "250 WORTMAN",
                        "245 COZINE",
                        "213 COZINE",
                        "215 COZINE",
                        "217 COZINE",
                        "195 COZINE",
                        "270 WORTMAN",
                        "300 WORTMAN",
                        "295 COZINE",
                        "285 COZINE",
                        "696 STANLEY",
                        "670 STANLEY",
                        "875 PENNSYLVANIA",
                        "877 PENNSYLVANIA",
                        "879 PENNSYLVANIA",
                        "881 PENNSYLVANIA",
                        "895 PENNSYLVANIA",
                        "155 WORTMAN",
                        "920 VERMONT",
                        "520 STANLEY",
                        "530 STANLEY",
                        "139 SCHOLES",
                        "174 LEONARD",
                        "87 TEN EYCK WALK",
                        "176 LEONARD",
                        "178 LEONARD",
                        "89 TEN EYCK WALK",
                        "92 MAUJER",
                        "90 MAUJER",
                        "94 MAUJER",
                        "91 TEN EYCK WALK",
                        "93 TEN EYCK WALK",
                        "95 TEN EYCK WALK",
                        "109 TEN EYCK WALK",
                        "110 MAUJER",
                        "108 MAUJER",
                        "114 MAUJER",
                        "112 MAUJER",
                        "111 TEN EYCK WALK",
                        "113 TEN EYCK WALK",
                        "90 TEN EYCK WALK",
                        "92 TEN EYCK WALK",
                        "101 STAGG WALK",
                        "99 STAGG WALK",
                        "97 STAGG WALK",
                        "110 TEN EYCK WALK",
                        "112 TEN EYCK WALK",
                        "114 TEN EYCK WALK",
                        "123 STAGG WALK",
                        "125 STAGG WALK",
                        "88 STAGG WALK",
                        "95 SCHOLES",
                        "93 SCHOLES",
                        "91 SCHOLES",
                        "101 SCHOLES",
                        "99 SCHOLES",
                        "97 SCHOLES",
                        "106 STAGG WALK",
                        "108 STAGG WALK",
                        "110 STAGG WALK",
                        "111 SCHOLES",
                        "115 SCHOLES",
                        "113 SCHOLES",
                        "112 STAGG WALK",
                        "114 STAGG WALK",
                        "123 TEN EYCK WALK",
                        "125 TEN EYCK WALK",
                        "126 MAUJER",
                        "124 MAUJER",
                        "128 MAUJER",
                        "127 TEN EYCK WALK",
                        "129 TEN EYCK WALK",
                        "131 TEN EYCK WALK",
                        "143 TEN EYCK WALK",
                        "145 TEN EYCK WALK",
                        "237 GRAHAM",
                        "239 GRAHAM",
                        "144 MAUJER",
                        "142 MAUJER",
                        "241 GRAHAM",
                        "243 GRAHAM",
                        "245 GRAHAM",
                        "247 GRAHAM",
                        "146 MAUJER",
                        "152 MAUJER",
                        "147 TEN EYCK WALK",
                        "235 GRAHAM",
                        "149 TEN EYCK WALK",
                        "231 GRAHAM",
                        "233 GRAHAM",
                        "151 TEN EYCK WALK",
                        "238 GRAHAM",
                        "240 GRAHAM",
                        "242 GRAHAM",
                        "161 TEN EYCK WALK",
                        "244 GRAHAM",
                        "246 GRAHAM",
                        "248 GRAHAM",
                        "163 TEN EYCK WALK",
                        "162 MAUJER",
                        "250 GRAHAM",
                        "252 GRAHAM",
                        "254 GRAHAM",
                        "160 MAUJER",
                        "164 MAUJER",
                        "165 TEN EYCK WALK",
                        "167 TEN EYCK WALK",
                        "169 TEN EYCK WALK",
                        "183 TEN EYCK WALK",
                        "180 MAUJER",
                        "176 MAUJER",
                        "178 MAUJER",
                        "182 MAUJER",
                        "184 MAUJER",
                        "185 TEN EYCK WALK",
                        "187 TEN EYCK WALK",
                        "222 GRAHAM",
                        "164 TEN EYCK WALK",
                        "166 TEN EYCK WALK",
                        "168 TEN EYCK WALK",
                        "169 STAGG WALK",
                        "181 STAGG WALK",
                        "186 TEN EYCK WALK",
                        "188 TEN EYCK WALK",
                        "190 TEN EYCK WALK",
                        "197 STAGG WALK",
                        "199 STAGG WALK",
                        "202 GRAHAM",
                        "210 GRAHAM",
                        "212 GRAHAM",
                        "214 GRAHAM",
                        "160 STAGG WALK",
                        "165 SCHOLES",
                        "206 GRAHAM",
                        "208 GRAHAM",
                        "163 SCHOLES",
                        "204 GRAHAM",
                        "159 SCHOLES",
                        "161 SCHOLES",
                        "167 SCHOLES",
                        "169 SCHOLES",
                        "171 SCHOLES",
                        "181 SCHOLES",
                        "182 STAGG WALK",
                        "180 STAGG WALK",
                        "178 STAGG WALK",
                        "186 STAGG WALK",
                        "184 STAGG WALK",
                        "183 SCHOLES",
                        "185 SCHOLES",
                        "197 TEN EYCK WALK",
                        "199 TEN EYCK WALK",
                        "198 MAUJER",
                        "196 MAUJER",
                        "200 MAUJER",
                        "201 TEN EYCK WALK",
                        "203 TEN EYCK WALK",
                        "205 TEN EYCK WALK",
                        "219 TEN EYCK WALK",
                        "216 MAUJER",
                        "214 MAUJER",
                        "136 BUSHWICK",
                        "138 BUSHWICK",
                        "220 MAUJER",
                        "218 MAUJER",
                        "128 BUSHWICK",
                        "130 BUSHWICK",
                        "132 BUSHWICK",
                        "134 BUSHWICK",
                        "221 TEN EYCK WALK",
                        "122 BUSHWICK",
                        "124 BUSHWICK",
                        "223 TEN EYCK WALK",
                        "200 TEN EYCK WALK",
                        "202 TEN EYCK WALK",
                        "211 STAGG WALK",
                        "213 STAGG WALK",
                        "215 STAGG WALK",
                        "222 TEN EYCK WALK",
                        "224 TEN EYCK WALK",
                        "226 TEN EYCK WALK",
                        "233 STAGG WALK",
                        "235 STAGG WALK",
                        "196 STAGG WALK",
                        "199 SCHOLES",
                        "197 SCHOLES",
                        "195 SCHOLES",
                        "201 SCHOLES",
                        "203 SCHOLES",
                        "205 SCHOLES",
                        "215 SCHOLES",
                        "218 STAGG WALK",
                        "216 STAGG WALK",
                        "214 STAGG WALK",
                        "178 BUSHWICK",
                        "222 STAGG WALK",
                        "172 BUSHWICK",
                        "176 BUSHWICK",
                        "220 STAGG WALK",
                        "217 SCHOLES",
                        "219 SCHOLES",
                        "195 GRAHAM",
                        "752 FENIMORE",
                        "750 FENIMORE",
                        "748 FENIMORE",
                        "746 FENIMORE",
                        "742 FENIMORE",
                        "740 FENIMORE",
                        "738 FENIMORE",
                        "736 FENIMORE",
                        "732 FENIMORE",
                        "730 FENIMORE",
                        "728 FENIMORE",
                        "726 FENIMORE",
                        "334 LEFFERTS",
                        "336 LEFFERTS",
                        "338 LEFFERTS",
                        "340 LEFFERTS",
                        "342 LEFFERTS",
                        "344 LEFFERTS",
                        "1142 LENOX ROAD",
                        "1144 LENOX ROAD",
                        "1145 LENOX ROAD",
                        "1180 EAST NEW YORK",
                        "1186 EAST NEW YORK",
                        "662 RALPH",
                        "1196 EAST NEW YORK",
                        "672 RALPH",
                        "682 RALPH",
                        "692 RALPH",
                        "698 RALPH",
                        "720 EAST NEW YORK",
                        "722 EAST NEW YORK",
                        "726 EAST NEW YORK",
                        "728 EAST NEW YORK",
                        "730 EAST NEW YORK",
                        "681 MAPLE",
                        "955 RUTLAND ROAD",
                        "114 WEST 139TH",
                        "155 WEST 142ND",
                        "157 WEST 142ND",
                        "111 WEST 143RD",
                        "113 WEST 143RD",
                        "155 WEST 143RD",
                        "157 WEST 143RD",
                        "109 WEST 144TH",
                        "113 WEST 144TH",
                        "117 WEST 144TH",
                        "125 WEST 144TH",
                        "129 WEST 144TH",
                        "133 WEST 144TH",
                        "148 WEST 144TH",
                        "158 WEST 144TH",
                        "162 WEST 144TH",
                        "2537 A C POWELL",
                        "164 WEST 147TH",
                        "2533 A C POWELL",
                        "2529 A C POWELL",
                        "2525 A C POWELL",
                        "2477 A C POWELL",
                        "164 WEST 144TH",
                        "2473 A C POWELL",
                        "2469 A C POWELL",
                        "2465 A C POWELL",
                        "2461 A C POWELL",
                        "167 WEST 143RD",
                        "163 WEST 143RD",
                        "159 WEST 143RD",
                        "151 WEST 143RD",
                        "145 WEST 143RD",
                        "143 WEST 143RD",
                        "135 WEST 143RD",
                        "131 WEST 143RD",
                        "649 MALCOLM X",
                        "645 MALCOLM X",
                        "129 WEST 142ND",
                        "141 WEST 142ND",
                        "143 WEST 142ND",
                        "145 WEST 142ND",
                        "149 WEST 142ND",
                        "2453 A C POWELL",
                        "2449 A C POWELL",
                        "2441 A C POWELL",
                        "144 WEST 141 ST",
                        "2409 A C POWELL",
                        "2407 A C POWELL",
                        "116 WEST 139TH",
                        "112 WEST 139TH",
                        "669 LENOX",
                        "103 WEST 143RD",
                        "105 WEST 143RD",
                        "1895 SCHIEFFELIN",
                        "1180 GRENADA",
                        "1186 GRENADA",
                        "3881 BAYCHESTER",
                        "3885 BAYCHESTER",
                        "3861 BAYCHESTER",
                        "3865 BAYCHESTER",
                        "3841 BAYCHESTER",
                        "3845 BAYCHESTER",
                        "1981 SCHIEFFELIN",
                        "1985 SCHIEFFELIN",
                        "1961 SCHIEFFELIN",
                        "1965 SCHIEFFELIN",
                        "1173 229TH",
                        "1159 229TH",
                        "1161 229TH",
                        "1147 229TH",
                        "1149 229TH",
                        "1166 GRENADA",
                        "1160 GRENADA",
                        "1137 229TH",
                        "1139 229TH",
                        "1125 229TH",
                        "1127 229TH",
                        "1107 EAST 229TH",
                        "1111 EAST 229TH",
                        "1126 229TH",
                        "1135 EAST 229TH",
                        "1141 EAST 229TH",
                        "1146 229TH",
                        "1145 EAST 229TH",
                        "1151 EAST 229TH",
                        "1165 EAST 229TH",
                        "1175 EAST 229TH",
                        "1189 229TH",
                        "1195 EAST 229TH",
                        "1170 229TH",
                        "1135 229TH",
                        "1153 229TH",
                        "1155 229TH",
                        "1130 229TH",
                        "1132 229TH",
                        "1128 EAST 229TH",
                        "1120 EAST 229TH",
                        "4044 LACONIA",
                        "4040 LACONIA",
                        "4056 LACONIA",
                        "4064 LACONIA",
                        "4020 LACONIA",
                        "4024 LACONIA",
                        "4034 LACONIA",
                        "4030 LACONIA",
                        "1138 229TH",
                        "1154 229TH",
                        "1160 229TH",
                        "1187 226TH",
                        "1183 226TH",
                        "1169 226TH",
                        "1165 226TH",
                        "1145 226TH",
                        "1151 226TH",
                        "1141 226TH",
                        "1131 226TH",
                        "1135 226TH",
                        "4000 LACONIA",
                        "4010 LACONIA",
                        "1115 EAST 225TH",
                        "1121 EAST 225TH",
                        "1138 226TH",
                        "1130 226TH",
                        "1155 EAST 225TH",
                        "1161 EAST 225TH",
                        "1181 EAST 225TH",
                        "1175 EAST 225TH",
                        "1195 EAST 225TH",
                        "1855 SCHIEFFELIN",
                        "1140 EAST 229TH",
                        "1150 EAST 229TH",
                        "1149GAR 229TH",
                        "104 TAPSCOTT",
                        "114 TAPSCOTT",
                        "182 TAPSCOTT",
                        "188 TAPSCOTT",
                        "190 TAPSCOTT",
                        "725 HOWARD",
                        "728 HOWARD",
                        "738 HOWARD",
                        "170 TAPSCOTT",
                        "175 TAPSCOTT",
                        "185 TAPSCOTT",
                        "184 TAPSCOTT",
                        "187 TAPSCOTT",
                        "197 TAPSCOTT",
                        "192 TAPSCOTT",
                        "199 TAPSCOTT",
                        "209 TAPSCOTT",
                        "2041 UNION",
                        "2063 UNION",
                        "2067 UNION",
                        "2069 UNION",
                        "2079 UNION",
                        "2045 UNION",
                        "2055 UNION",
                        "2058 UNION",
                        "2068 UNION",
                        "1634 STERLING",
                        "1367 SAINT MARKS",
                        "1371 SAINT MARKS",
                        "1629 PARK",
                        "1630 PARK",
                        "1636 PARK",
                        "1640 PARK",
                        "1646 PARK",
                        "905 EAGLE",
                        "907 EAGLE",
                        "43 TAPSCOTT",
                        "32 GRAFTON",
                        "36 GRAFTON",
                        "40 GRAFTON",
                        "44 GRAFTON",
                        "48 GRAFTON",
                        "571 HOWARD",
                        "575 HOWARD",
                        "579 HOWARD",
                        "583 HOWARD",
                        "587 HOWARD",
                        "591 HOWARD",
                        "595 HOWARD",
                        "599 HOWARD",
                        "603 HOWARD",
                        "607 HOWARD",
                        "611 HOWARD",
                        "574 HOWARD",
                        "578 HOWARD",
                        "582 HOWARD",
                        "602 HOWARD",
                        "606 HOWARD",
                        "610 HOWARD",
                        "614 HOWARD",
                        "1 TAPSCOTT",
                        "5 TAPSCOTT",
                        "9 TAPSCOTT",
                        "13 TAPSCOTT",
                        "17 TAPSCOTT",
                        "1481 EASTERN PARKWAY",
                        "1483 EASTERN PARKWAY",
                        "1485 EASTERN PARKWAY",
                        "486 HOWARD",
                        "488 HOWARD",
                        "490 HOWARD",
                        "492 HOWARD",
                        "500 HOWARD",
                        "502 HOWARD",
                        "514 HOWARD",
                        "1695 SAINT JOHNS",
                        "1697 SAINT JOHNS",
                        "1701 SAINT JOHNS",
                        "1703 SAINT JOHNS",
                        "1747 SAINT JOHNS",
                        "1749 SAINT JOHNS",
                        "1751 SAINT JOHNS",
                        "1753 SAINT JOHNS",
                        "1755 SAINT JOHNS",
                        "1757 SAINT JOHNS",
                        "1738 STERLING",
                        "1740 STERLING",
                        "1758 STERLING",
                        "543B RALPH",
                        "545 RALPH",
                        "545A RALPH",
                        "545B RALPH",
                        "547 RALPH",
                        "547A RALPH",
                        "547B RALPH",
                        "549 RALPH",
                        "549A RALPH",
                        "549B RALPH",
                        "551 RALPH",
                        "551A RALPH",
                        "551B RALPH",
                        "553 RALPH",
                        "555 RALPH",
                        "1649 SAINT JOHNS",
                        "1651 SAINT JOHNS",
                        "1659 SAINT JOHNS",
                        "1720 STERLING",
                        "1720A STERLING",
                        "1720B STERLING",
                        "1722 STERLING",
                        "1722A STERLING",
                        "1722B STERLING",
                        "1724 STERLING",
                        "1724A STERLING",
                        "1724B STERLING",
                        "1726 STERLING",
                        "1726A STERLING",
                        "1726B STERLING",
                        "1728 STERLING",
                        "1728A STERLING",
                        "1728B STERLING",
                        "1730 STERLING",
                        "1730A STERLING",
                        "1730B STERLING",
                        "1732 STERLING",
                        "1732A STERLING",
                        "1732B STERLING",
                        "1734 STERLING",
                        "1734A STERLING",
                        "1734B STERLING",
                        "1736 STERLING",
                        "1736A STERLING",
                        "1736B STERLING",
                        "497 HOWARD",
                        "497A HOWARD",
                        "497B HOWARD",
                        "499 HOWARD",
                        "499A HOWARD",
                        "499B HOWARD",
                        "501 HOWARD",
                        "501A HOWARD",
                        "501B HOWARD",
                        "503 HOWARD",
                        "503A HOWARD",
                        "503B HOWARD",
                        "505 HOWARD",
                        "505A HOWARD",
                        "505B HOWARD",
                        "507 HOWARD",
                        "507A HOWARD",
                        "507B HOWARD",
                        "509 HOWARD",
                        "509A HOWARD",
                        "509B HOWARD",
                        "511 HOWARD",
                        "511A HOWARD",
                        "511B HOWARD",
                        "513 HOWARD",
                        "515 HOWARD",
                        "1737 SAINT JOHNS",
                        "1745 SAINT JOHNS",
                        "1790 STERLING",
                        "1790A STERLING",
                        "1790B STERLING",
                        "1792 STERLING",
                        "1792A STERLING",
                        "1792B STERLING",
                        "1794 STERLING",
                        "1794A STERLING",
                        "1794B STERLING",
                        "1796 STERLING",
                        "1796A STERLING",
                        "1796B STERLING",
                        "1798 STERLING",
                        "1798A STERLING",
                        "1798B STERLING",
                        "1800 STERLING",
                        "1800A STERLING",
                        "1800B STERLING",
                        "1802 STERLING",
                        "1802A STERLING",
                        "1802B STERLING",
                        "1804 STERLING",
                        "1804A STERLING",
                        "1804B STERLING",
                        "1806 STERLING",
                        "1810 STERLING",
                        "1812 STERLING",
                        "1814 STERLING",
                        "2041 PACIFIC",
                        "334 HOWARD",
                        "336 HOWARD",
                        "324 HOWARD",
                        "2020 PACIFIC",
                        "2065 DEAN",
                        "1487 SAINT JOHNS",
                        "1483 SAINT JOHNS",
                        "1491 SAINT JOHNS",
                        "1506 STERLING",
                        "1511 STERLING",
                        "1640 STERLING",
                        "1448 STERLING",
                        "1452 STERLING",
                        "1568 STERLING",
                        "1578 STERLING",
                        "1588 STERLING",
                        "1598 STERLING",
                        "225 BUFFALO",
                        "1468 PARK",
                        "1474 PARK",
                        "1480 PARK",
                        "1484 PARK",
                        "208 ROCHESTER",
                        "218 ROCHESTER",
                        "1521 STERLING",
                        "230 ROCHESTER",
                        "1522 STERLING",
                        "232 ROCHESTER",
                        "1115 CLAY",
                        "1119 CLAY",
                        "1123 CLAY",
                        "1127 CLAY",
                        "1195 CLAY",
                        "1232 CLAY",
                        "1236 CLAY",
                        "1244 CLAY",
                        "1278 CLAY",
                        "1280 CLAY",
                        "1052 TELLER",
                        "1064 TELLER",
                        "1072 TELLER",
                        "1105 TELLER",
                        "1109 TELLER",
                        "1113 TELLER",
                        "1117 TELLER",
                        "1129 TELLER",
                        "1252 CLAY",
                        "1248 CLAY",
                        "1240 CLAY",
                        "1228 CLAY",
                        "1122 FINDLAY",
                        "1124 FINDLAY",
                        "1128 FINDLAY",
                        "1134 FINDLAY",
                        "1114 FINDLAY",
                        "335 EAST 166TH",
                        "1068 TELLER",
                        "1046 TELLER",
                        "1105 FINDLAY",
                        "1129 FINDLAY",
                        "1150 COLLEGE",
                        "1156 COLLEGE",
                        "308 EAST 167TH",
                        "1131 FINDLAY",
                        "1113 FINDLAY",
                        "1117 FINDLAY",
                        "1121 FINDLAY",
                        "1930 HARRISON",
                        "1886 HARRISON",
                        "1920 HARRISON",
                        "1925 HARRISON",
                        "1934 HARRISON",
                        "48 WEST 94TH",
                        "50 WEST 94TH",
                        "52 WEST 94TH",
                        "54 WEST 94TH",
                        "845 CAULDWELL",
                        "851 CAULDWELL",
                        "855 CAULDWELL",
                        "861 CAULDWELL",
                        "865 CAULDWELL",
                        "821 CAULDWELL",
                        "825 CAULDWELL",
                        "829 CAULDWELL",
                        "611 EAST 158TH",
                        "615 EAST 158TH",
                        "625 EAST 158TH",
                        "635 EAST 158TH",
                        "645 EAST 158TH",
                        "854 EAGLE",
                        "850 EAGLE",
                        "844 EAGLE",
                        "840 EAGLE",
                        "834 EAGLE",
                        "830 EAGLE",
                        "839 REV JAMES A POLITE",
                        "845 REV JAMES A POLITE",
                        "851 REV JAMES A POLITE",
                        "857 REV JAMES A POLITE",
                        "863 REV JAMES A POLITE",
                        "869 REV JAMES A POLITE",
                        "875 REV JAMES A POLITE",
                        "881 REV JAMES A POLITE",
                        "820 HEWITT",
                        "826 HEWITT",
                        "832 HEWITT",
                        "840 HEWITT",
                        "846 HEWITT",
                        "852 HEWITT",
                        "950 UNION",
                        "1143 LONGFELLOW",
                        "125 WEST 93RD",
                        "143 WEST 93RD",
                        "22 WEST 91ST",
                        "24 WEST 91ST",
                        "26 WEST 91ST",
                        "28 WEST 91ST",
                        "30 WEST 91ST",
                        "32 WEST 91ST",
                        "34 WEST 91ST",
                        "36 WEST 91ST",
                        "38 WEST 91ST",
                        "127 WEST 93RD",
                        "40 WEST 91ST",
                        "42 WEST 91ST",
                        "64 WEST 91ST",
                        "66 WEST 91ST",
                        "68 WEST 91ST",
                        "70 WEST 91ST",
                        "15 WEST 90TH",
                        "17 WEST 90TH",
                        "19 WEST 90TH",
                        "21 WEST 90TH",
                        "129 WEST 93RD",
                        "23 WEST 90TH",
                        "38 WEST 90TH",
                        "40 WEST 90TH",
                        "42 WEST 90TH",
                        "47 WEST 89TH",
                        "49 WEST 89TH",
                        "51 WEST 89TH",
                        "131 WEST 93RD",
                        "133 WEST 93RD",
                        "135 WEST 93RD",
                        "137 WEST 93RD",
                        "139 WEST 93RD",
                        "141 WEST 93RD",
                        "1700 HOE",
                        "1707 BRYANT",
                        "1527 HOE",
                        "1531 HOE",
                        "1533 HOE",
                        "1535 HOE",
                        "1537 HOE",
                        "1545 HOE",
                        "1551 HOE",
                        "1557 HOE",
                        "1563 HOE",
                        "1463 VYSE",
                        "1465 VYSE",
                        "1467 VYSE",
                        "1469 VYSE",
                        "1471 VYSE",
                        "1475 VYSE",
                        "1477 VYSE",
                        "1479 VYSE",
                        "1481 VYSE",
                        "1485 VYSE",
                        "1487 VYSE",
                        "1489 VYSE",
                        "1491 VYSE",
                        "1493 VYSE",
                        "941 EAST 172ND",
                        "1520 HOE",
                        "1524 HOE",
                        "1528 HOE",
                        "1550 HOE",
                        "1554 HOE",
                        "1558 HOE",
                        "1566 HOE",
                        "1570 HOE",
                        "1572 HOE",
                        "1576 HOE",
                        "1580 HOE",
                        "1579 VYSE",
                        "1575 VYSE",
                        "1571 VYSE",
                        "2021 BOSTON ROAD",
                        "1010 EAST 178TH",
                        "1012 EAST 178TH",
                        "1030 EAST 178TH",
                        "1070 FAILE",
                        "1071 BRYANT",
                        "1084 BRYANT",
                        "1080 BRYANT",
                        "1074 BRYANT",
                        "1070 BRYANT",
                        "1134 EAST 165TH",
                        "1130 EAST 165TH",
                        "1124 EAST 165TH",
                        "1120 EAST 165TH",
                        "1040 BRYANT",
                        "1034 BRYANT",
                        "1030 BRYANT",
                        "1024 BRYANT",
                        "1020 BRYANT",
                        "1080 EAST 165TH",
                        "1084 EAST 165TH",
                        "1090 EAST 165TH",
                        "1094 EAST 165TH",
                        "1100 EAST 165TH",
                        "1110 EAST 165TH",
                        "819 HUNTS POINT",
                        "823 HUNTS POINT",
                        "859 HUNTS POINT",
                        "863 HUNTS POINT",
                        "867 HUNTS POINT",
                        "875 IRVINE",
                        "827 HUNTS POINT",
                        "831 HUNTS POINT",
                        "835 HUNTS POINT",
                        "839 HUNTS POINT",
                        "843 HUNTS POINT",
                        "847 HUNTS POINT",
                        "851 HUNTS POINT",
                        "855 HUNTS POINT",
                        "1091 LONGFELLOW",
                        "1102 LONGFELLOW",
                        "1209 WESTCHESTER",
                        "1002 EAST 167TH",
                        "998 EAST 167TH",
                        "1317 WEST FARMS ROAD",
                        "1321 WEST FARMS ROAD",
                        "1323 WEST FARMS ROAD",
                        "1471 WATSON",
                        "1473 WATSON",
                        "1052 BOYNTON",
                        "1044 BOYNTON",
                        "1048 BOYNTON",
                        "1057 BOYNTON",
                        "1162 WASHINGTON",
                        "1174 WASHI NGTON",
                        "1176 WASHI NGTON",
                        "1020 COLLEGE",
                        "1030 COLLEGE",
                        "1100 TELLER",
                        "1110 TELLER",
                        "1525 FULTON",
                        "1531 FULTON",
                        "1535 FULTON",
                        "1545 FULTON",
                        "1150 UNION",
                        "1152 UNION",
                        "818 HOME",
                        "1221 PROSPECT",
                        "1135 PROSPECT",
                        "819 EAST 167TH",
                        "817 EAST 167TH",
                        "815 EAST 167TH",
                        "813 EAST 167TH",
                        "811 EAST 167TH",
                        "1104 UNION",
                        "1102 UNION",
                        "1100 UNION",
                        "1098 UNION",
                        "1096 UNION",
                        "815 EAST 166TH",
                        "817 EAST 166TH",
                        "819 EAST 166TH",
                        "822 EAST 167TH",
                        "820 EAST 167TH",
                        "818 EAST 167TH",
                        "1111 PROSPECT",
                        "1113 PROSPECT",
                        "1115 PROSPECT",
                        "1710 LAFAYETTE",
                        "750 CROES",
                        "710 CROES",
                        "715 NOBLE",
                        "710 NOBLE",
                        "712 NOBLE",
                        "740 BEACH",
                        "1810 LAFAYETTE",
                        "717GAR NOBLE",
                        "865 NOBLE",
                        "867 NOBLE",
                        "869 NOBLE",
                        "871 NOBLE",
                        "873 NOBLE",
                        "10 CLASON POINT LANE",
                        "12 CLASON POINT LANE",
                        "14 CLASON POINT LANE",
                        "16 CLASON POINT LANE",
                        "18 CLASON POINT LANE",
                        "20 CLASON POINT LANE",
                        "22 CLASON POINT LANE",
                        "1690 STORY",
                        "1692 STORY",
                        "1694 STORY",
                        "1698 STORY",
                        "1682 STORY",
                        "1684 STORY",
                        "1686 STORY",
                        "1688 STORY",
                        "30 CLASON POINT LANE",
                        "32 CLASON POINT LANE",
                        "34 CLASON POINT LANE",
                        "36 CLASON POINT LANE",
                        "38 CLASON POINT LANE",
                        "40 CLASON POINT LANE",
                        "42 CLASON POINT LANE",
                        "44 CLASON POINT LANE",
                        "46 CLASON POINT LANE",
                        "48 CLASON POINT LANE",
                        "50 CLASON POINT LANE",
                        "52 CLASON POINT LANE",
                        "54 CLASON POINT LANE",
                        "56 CLASON POINT LANE",
                        "58 CLASON POINT LANE",
                        "60 CLASON POINT LANE",
                        "62 CLASON POINT LANE",
                        "64 CLASON POINT LANE",
                        "66 CLASON POINT LANE",
                        "68 CLASON POINT LANE",
                        "70 CLASON POINT LANE",
                        "72 CLASON POINT LANE",
                        "74 CLASON POINT LANE",
                        "76 CLASON POINT LANE",
                        "78 CLASON POINT LANE",
                        "80 CLASON POINT LANE",
                        "82 CLASON POINT LANE",
                        "1660 STORY",
                        "1662 STORY",
                        "1664 STORY",
                        "1666 STORY",
                        "1668 STORY",
                        "857 NOBLE",
                        "859 NOBLE",
                        "861 NOBLE",
                        "863 NOBLE",
                        "856 METCALF",
                        "860 METCALF",
                        "864 METCALF",
                        "868 METCALF",
                        "872 METCALF",
                        "842 METCALF",
                        "844 METCALF",
                        "846 METCALF",
                        "848 METCALF",
                        "834 METCALF",
                        "836 METCALF",
                        "838 METCALF",
                        "840 METCALF",
                        "17 CLASON POINT LANE",
                        "19 CLASON POINT LANE",
                        "21 CLASON POINT LANE",
                        "23 CLASON POINT LANE",
                        "9 CLASON POINT LANE",
                        "11 CLASON POINT LANE",
                        "15 CLASON POINT LANE",
                        "1 CLASON POINT LANE",
                        "3 CLASON POINT LANE",
                        "5 CLASON POINT LANE",
                        "7 CLASON POINT LANE",
                        "1685 LAFAYETTE",
                        "1687 LAFAYETTE",
                        "1689 LAFAYETTE",
                        "1691 LAFAYETTE",
                        "1677 LAFAYETTE",
                        "1679 LAFAYETTE",
                        "1681 LAFAYETTE",
                        "1683 LAFAYETTE",
                        "1667 LAFAYETTE",
                        "1669 LAFAYETTE",
                        "1671 LAFAYETTE",
                        "1673 LAFAYETTE",
                        "1675 LAFAYETTE",
                        "810 METCALF",
                        "814 METCALF",
                        "818 METCALF",
                        "822 METCALF",
                        "826 METCALF",
                        "839 NOBLE",
                        "843 NOBLE",
                        "847 NOBLE",
                        "851 NOBLE",
                        "1661 LAFAYETTE",
                        "1663 LAFAYETTE",
                        "1665 LAFAYETTE",
                        "781 CROES",
                        "785 CROES",
                        "789 CROES",
                        "793 CROES",
                        "1682 LAFAYETTE",
                        "1684 LAFAYETTE",
                        "1686 LAFAYETTE",
                        "1683 CROES",
                        "1685 CROES",
                        "1687 CROES",
                        "1674 LAFAYETTE",
                        "1676 LAFAYETTE",
                        "1678 LAFAYETTE",
                        "1680 LAFAYETTE",
                        "1666 LAFAYETTE",
                        "1668 LAFAYETTE",
                        "1670 LAFAYETTE",
                        "1672 LAFAYETTE",
                        "1660 LAFAYETTE",
                        "1662 LAFAYETTE",
                        "1664 LAFAYETTE",
                        "780 METCALF",
                        "784 METCALF",
                        "788 METCALF",
                        "768 METCALF",
                        "770 METCALF",
                        "772 METCALF",
                        "774 METCALF",
                        "750 METCALF",
                        "752 METCALF",
                        "754 METCALF",
                        "756 METCALF",
                        "2 CLASON POINT LANE",
                        "4 CLASON POINT LANE",
                        "6 CLASON POINT LANE",
                        "8 CLASON POINT LANE",
                        "738 METCALF",
                        "740 METCALF",
                        "742 METCALF",
                        "744 METCALF",
                        "720 METCALF",
                        "722 METCALF",
                        "724 METCALF",
                        "726 METCALF",
                        "758 METCALF",
                        "760 METCALF",
                        "762 METCALF",
                        "764 METCALF",
                        "766 METCALF",
                        "728 METCALF",
                        "730 METCALF",
                        "732 METCALF",
                        "734 METCALF",
                        "736 METCALF",
                        "1671 SEWARD",
                        "1673 SEWARD",
                        "1675 SEWARD",
                        "1677 SEWARD",
                        "1663 SEWARD",
                        "1665 SEWARD",
                        "1667 SEWARD",
                        "1669 SEWARD",
                        "700 METCALF",
                        "704 METCALF",
                        "708 METCALF",
                        "712 METCALF",
                        "827 NOBLE",
                        "829 NOBLE",
                        "831 NOBLE",
                        "833 NOBLE",
                        "819 NOBLE",
                        "821 NOBLE",
                        "823 NOBLE",
                        "825 NOBLE",
                        "1719 LAFAYETTE",
                        "801 NOBLE",
                        "805 NOBLE",
                        "807 NOBLE",
                        "809 NOBLE",
                        "811 NOBLE",
                        "1705 LAFAYETTE",
                        "1707 LAFAYETTE",
                        "1709 LAFAYETTE",
                        "1711 LAFAYETTE",
                        "1697 LAFAYETTE",
                        "1699 LAFAYETTE",
                        "1701 LAFAYETTE",
                        "1703 LAFAYETTE",
                        "305 EAST 101ST",
                        "307 EAST 101ST",
                        "302 EAST 102ND",
                        "304 EAST 102ND",
                        "306 EAST 102ND",
                        "308 EAST 102ND",
                        "310 EAST 102ND",
                        "312 EAST 102ND",
                        "320 EAST 102ND",
                        "342 EAST 102ND",
                        "345 EAST 101ST",
                        "347 EAST 101ST",
                        "2029 2ND",
                        "2031 2ND",
                        "231 EAST 104TH",
                        "237 EAST 104TH",
                        "2040 1ST",
                        "405 EAST 105TH",
                        "407 EAST 105TH",
                        "410 EAST 106TH",
                        "425 EAST 105TH",
                        "435 EAST 105TH",
                        "701 WILLOUGHBY",
                        "671 WILLOUGHBY",
                        "675 WILLOUGHBY",
                        "281 THROOP",
                        "213 HART",
                        "946 HANCOCK",
                        "881 HALSEY",
                        "940 HANCOCK",
                        "23 SARATOGA",
                        "33 SARATOGA",
                        "35 SARATOGA",
                        "857 GATES",
                        "859 GATES",
                        "863 GATES",
                        "245 LEWIS",
                        "714 GATES",
                        "720 GATES",
                        "730 GATES",
                        "734 GATES",
                        "740 GATES",
                        "744 GATES",
                        "750 GATES",
                        "760 GATES",
                        "770 GATES",
                        "210 STUYVESANT",
                        "214 STUYVESANT",
                        "220 STUYVESANT",
                        "585 MONROE",
                        "855 GATES",
                        "845 GATES",
                        "835 GATES",
                        "841 GATES",
                        "185 STUYVESANT",
                        "175 STUYVESANT",
                        "680 QUINCY",
                        "690 QUINCY",
                        "700 QUINCY",
                        "706 QUINCY",
                        "885 GATES",
                        "881 GATES",
                        "875 GATES",
                        "865 GATES",
                        "128 MALCOLM X",
                        "150 MALCOLM X",
                        "301 MACDOUGAL",
                        "24 MOTHER GASTON",
                        "26 MOTHER GASTON",
                        "30 MOTHER GASTON",
                        "15 MOTHER GASTON",
                        "17 MOTHER GASTON",
                        "305 MACDOUGAL",
                        "309 MACDOUGAL",
                        "311 MACDOUGAL",
                        "319 MACDOUGAL",
                        "386 SUMPTER",
                        "17 EAST 124TH",
                        "110 EAST 129TH",
                        "111 EAST 128TH",
                        "2120 LEXINGTON",
                        "1980 LEXINGTON",
                        "1940 LEXINGTON",
                        "307 EAST 116TH",
                        "306 EAST 117TH",
                        "218 WEST 112TH",
                        "224 WEST 112TH",
                        "1940 A C POWELL",
                        "1942 A C POWELL",
                        "1944 A C POWELL",
                        "1946 A C POWELL",
                        "201 WEST 117TH",
                        "146 SAINT NICHOLAS",
                        "203 WEST 117TH",
                        "180 LENOX",
                        "184 LENOX",
                        "95 WEST 119TH",
                        "131 SAINT NICHOLAS",
                        "2021 BOSTON",
                        "1010 EAST 178TH",
                        "1030 EAST 178TH",
                        "1012 EAST 178TH",
                        "2111 LAFONTAINE",
                        "2125 LAFONTAINE",
                        "2100 MONTEREY",
                        "2110 MONTEREY",
                        "554 EAST 181ST",
                        "558 EAST 181ST",
                        "560 EAST 181ST",
                        "2120 MONTEREY",
                        "2120 QUARRY",
                        "N/A OAKLAND PLACE",
                        "2070 CLINTON",
                        "2660 BAILEY",
                        "2661 HEATH",
                        "2663 HEATH",
                        "2667 HEATH",
                        "230 WEST 193RD",
                        "3340 BAILEY",
                        "3350 BAILEY",
                        "3353 FORT INDEPENDENCE",
                        "3355 FORT INDEPENDENCE",
                        "1930 HARRISON",
                        "1886 HARRISON",
                        "1920 HARRISON",
                        "1925 HARRISON",
                        "1934 HARRISON",
                        "1921 UNIVERSITY",
                        "1865 UNIVERSITY",
                        "1875 UNIVERSITY",
                        "1895 UNIVERSITY",
                        "1925 UNIVERSITY",
                        "1927 UNIVERSITY",
                        "228 WEST TREMONT",
                        "3475 BIVONA",
                        "3485 BIVONA",
                        "3545 BIVONA",
                        "3555 BIVONA",
                        "3565 BIVONA",
                        "3540 BIVONA",
                        "3550 BIVONA",
                        "3560 BIVONA",
                        "3570 BIVONA",
                        "3580 BIVONA",
                        "2175 REEDS MILL",
                        "2185 REEDS MILL",
                        "2185GAR REEDS MILL",
                        "3540 BIVONA",
                        "2185 REEDS MILL",
                        "2185GAR REEDS MILL",
                        "3540 BIVONA",
                        "3031 MIDDLETOWN",
                        "3033 MIDDLETOWN",
                        "3035 MIDDLETOWN",
                        "1705 BRYANT",
                        "1707 BRYANT",
                        "1070 FAILE",
                        "1071 BRYANT",
                        "1084 BRYANT",
                        "1080 BRYANT",
                        "1074 BRYANT",
                        "1070 BRYANT",
                        "1134 EAST 165TH",
                        "1130 EAST 165TH",
                        "1124 EAST 165TH",
                        "1120 EAST 165TH",
                        "1040 BRYANT",
                        "1034 BRYANT",
                        "1030 BRYANT",
                        "1024 BRYANT",
                        "1020 BRYANT",
                        "1080 EAST 165TH",
                        "1084 EAST 165TH",
                        "1090 EAST 165TH",
                        "1094 EAST 165TH",
                        "1100 EAST 165TH",
                        "1110 EAST 165TH",
                        "1527 HOE",
                        "1531 HOE",
                        "1533 HOE",
                        "1535 HOE",
                        "1537 HOE",
                        "1545 HOE",
                        "1551 HOE",
                        "1557 HOE",
                        "1563 HOE",
                        "1506 HOE",
                        "1460 HOE",
                        "1463 VYSE",
                        "1465 VYSE",
                        "1467 VYSE",
                        "1469 VYSE",
                        "1471 VYSE",
                        "1475 VYSE",
                        "1477 VYSE",
                        "1479 VYSE",
                        "1481 VYSE",
                        "1485 VYSE",
                        "1487 VYSE",
                        "1489 VYSE",
                        "1491 VYSE",
                        "1493 VYSE",
                        "941 EAST 172ND",
                        "1520 HOE",
                        "1524 HOE",
                        "1528 HOE",
                        "1550 HOE",
                        "1554 HOE",
                        "1558 HOE",
                        "1566 HOE",
                        "1570 HOE",
                        "1572 HOE",
                        "1576 HOE",
                        "1580 HOE",
                        "1579 VYSE",
                        "1575 VYSE",
                        "1571 VYSE",
                        "1700 HOE",
                        "819 HUNTS POINT",
                        "823 HUNTS POINT",
                        "859 HUNTS POINT",
                        "863 HUNTS POINT",
                        "867 HUNTS POINT",
                        "875 IRVINE",
                        "827 HUNTS POINT",
                        "831 HUNTS POINT",
                        "835 HUNTS POINT",
                        "839 HUNTS POINT",
                        "843 HUNTS POINT",
                        "847 HUNTS POINT",
                        "851 HUNTS POINT",
                        "855 HUNTS POINT",
                        "1091 LONGFELLOW",
                        "1102 LONGFELLOW",
                        "1203 WESTCHESTER",
                        "1209 WESTCHESTER",
                        "1002 EAST 167TH",
                        "998 EAST 167TH",
                        "1317 WEST FARMS",
                        "1321 WEST FARMS",
                        "1323 WEST FARMS",
                        "1143 LONGFELLOW",
                        "545 WEST 126TH",
                        "549 WEST 126TH",
                        "555 WEST 126TH",
                        "3240 BROADWAY",
                        "3250 BROADWAY",
                        "1414 AMSTERDAM",
                        "1420 AMSTERDAM",
                        "1470 AMSTERDAM",
                        "95 OLD BROADWAY",
                        "1430 AMSTERDAM",
                        "530 WEST 133RD",
                        "425 WEST 25TH",
                        "431 WEST 25TH",
                        "428 WEST 26TH",
                        "430 WEST 26TH",
                        "420 WEST 26TH",
                        "415 WEST 25TH",
                        "441 WEST 26TH",
                        "436 WEST 27TH DRIVE",
                        "288 10TH",
                        "455 WEST 26TH",
                        "459 WEST 26TH",
                        "450 WEST 27TH DRIVE",
                        "466 WEST 26TH",
                        "264 10TH ",
                        "457 WEST 25TH",
                        "446 WEST 26TH",
                        "443 WEST 25TH",
                        "447 WEST 25TH",
                        "427 WEST 26TH",
                        "426 WEST 27TH DRIVE",
                        "401 WEST 16TH",
                        "413 WEST 16TH",
                        "400 WEST 19TH",
                        "412 WEST 19TH",
                        "401 WEST 19TH",
                        "419 WEST 19TH",
                        "432GAR WEST 18TH",
                        "418 WEST 17TH",
                        "420 WEST 17TH",
                        "422 WEST 17TH",
                        "400 WEST 17TH",
                        "412 WEST 17TH",
                        "430 WEST 17TH",
                        "434 WEST 17TH",
                        "427 WEST 17TH",
                        "431 WEST 17TH",
                        "419 WEST 17TH",
                        "421 WEST 17TH",
                        "420 WEST 18TH",
                        "117 9TH",
                        "119 9TH",
                        "121 9TH",
                        "401 WEST 18TH  ",
                        "411 WEST 18TH",
                        "420 WEST 19TH",
                        "422 WEST 19TH"
                        "1161 ADEE",
                        "1130 BURKE",
                        "1134 BURKE",
                        "1140 BURKE",
                        "3016 YATES",
                        "3020 YATES",
                        "3010 YATES",
                        "1160 BURKE",
                        "1166 BURKE",
                        "1170 BURKE",
                        "1210 BURKE",
                        "1216 BURKE",
                        "1220 BURKE",
                        "1230 BURKE",
                        "1236 BURKE",
                        "1240 BURKE",
                        "1246 BURKE",
                        "1260 BURKE",
                        "3055 BOUCK",
                        "1255 ADEE ",
                        "1245 ADEE",
                        "1219 ADEE",
                        "1221 ADEE",
                        "372 EAST 152ND",
                        "370 EAST 153RD",
                        "550 CAULDWELL",
                        "595 TRINITY",
                        "670 CAULDWELL",
                        "645 WESTCHESTER",
                        "649 WESTCHESTER",
                        "665 WESTCHESTER",
                        "667 WESTCHESTER",
                        "700 EAST 156TH",
                        "671 WESTCHESTER",
                        "675 WESTCHESTER",
                        "679 WESTCHESTER",
                        "159-04 HARLEM RIVER",
                        "159-06 HARLEM RIVER",
                        "159-08 HARLEM RIVER",
                        "159-10 HARLEM RIVER",
                        "159-12 HARLEM RIVER",
                        "159-14 HARLEM RIVER",
                        "159-16 HARLEM RIVER",
                        "159-18 HARLEM RIVER",
                        "159-20 HARLEM RIVER",
                        "159-26 HARLEM RIVER",
                        "159-38 HARLEM RIVER",
                        "159-46 HARLEM RIVER",
                        "159-48 HARLEM RIVER",
                        "159-62 HARLEM RIVER",
                        "159-64 HARLEM RIVER",
                        "159-70 HARLEM RIVER",
                        "159-36 HARLEM RIVER",
                        "159-42 HARLEM RIVER",
                        "159-44 HARLEM RIVER",
                        "159-30 HARLEM RIVER",
                        "159-32 HARLEM RIVER",
                        "157 ALASKA",
                        "155 ALASKA ",
                        "1115 CASTLETON",
                        "1083 CASTLETON",
                        "1085 CASTLETON",
                        "1065 CASTLETON",
                        "260 BROADWAY ",
                        "244 BROADWAY",
                        "159 ALASKA",
                        "820 HENDERSON",
                        "778GAR HENDERSON",
                        "806 HENDERSON",
                        "780 HENDERSON",
                        "210 BROADWAY",
                        "770 HENDERSON",
                        "778 HENDERSON",
                        "810 HENDERSON ",
                        "814 HENDERSON",
                        "230 BROADWAY",
                        "240 BROADWAY",
                        "1077 CASTLETON",
                        "1075 CASTLETON",

                        ]
        
        #ignore case???
        #Function to search if a RAD address is in the case's street address
        def RADSearcher (ClientAddress):
            ClientAddress = str(ClientAddress)
            if any (radbuilding in ClientAddress.upper() for radbuilding in RADBuildings ):
                return "Possibly"
            else:
                return "Unlikely"
                       
        df['Potential RAD Case?'] = df.apply(lambda x : RADSearcher(x['Street Address']),axis=1)
        
        #Putting everything in the right order
        
        
        df = df[['Hyperlinked CaseID#','Assigned Branch/CC','Primary Advocate','Street Address','Apt#/Suite#','City','Zip Code','Potential RAD Case?','Legal Problem Code','Special Legal Problem Code','Gender','Race','Language','HUD Ethnicity','Do you identify as LGBT?','Immigration Status','HUD Veteran Status','Income Types','Is Domestic Violence a factor in this case?','Date of Birth','Date Opened','Date Closed','Close Reason','Case Disposition','Case Status','Outcome','Case Disposition','Housing Type Of Case','Housing Form Of Regulation','Housing Level of Service','Case Involves Covid-19','Combined Notes']]
        
        
        #Preparing Excel Document

        borough_dictionary = dict(tuple(df.groupby('Potential RAD Case?')))

        def save_xls(dict_df, path):
            writer = pd.ExcelWriter(path, engine = 'xlsxwriter')
            for i in dict_df:
                dict_df[i].to_excel(writer, i, index = False)
                workbook = writer.book
                link_format = workbook.add_format({'font_color':'blue','bold':True,'underline':True})
                problem_format = workbook.add_format({'bg_color':'yellow'})
                
                
                
                worksheet = writer.sheets[i]
                

                worksheet.set_column('A:A',15,link_format)
                worksheet.set_column('B:AF',20)
                
                    
                worksheet.conditional_format('D2:BO100000',{'type': 'text',
                                                         'criteria': 'containing',
                                                         'value': 'CSR No',
                                                         'format': problem_format})
                worksheet.freeze_panes(1,1)
            writer.save()
        output_filename = f.filename

        save_xls(dict_df = borough_dictionary, path = "app\\sheets\\" + output_filename)

        return send_from_directory('sheets',output_filename, as_attachment = True, attachment_filename = "Python " + f.filename)
        
        #***#
       
        
#what the user-facing site looks like
    return '''
    <!doctype html>
    <title>RAD Searcher</title>
    <link rel="stylesheet" href="/static/css/main.css">  
    <link rel="stylesheet" href="/static/css/main.css"> 
    <h1>Search for RAD Clients</h1>
    <form action="" method=post enctype=multipart/form-data>
    <p><input type=file name=file><input type=submit value=Determine!>
    
    </br>
    </br>

    
    </form>
    <h3>Instructions:</h3>
    <ul type="disc">
    <li>This tool is meant to be used in conjunction with the LegalServer report called <a href="https://lsnyc.legalserver.org/report/dynamic/?load=2373" target="_blank">Weekly Housing Intake Report</a>.</li>
    
    </ul>
    </br>
    <a href="/">Home</a>
    '''
    
